/* -*-c-*-
   The MIT License (MIT)

   Copyright (c) 2024 - Ronaldo Faria Lima

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.

   Created: 2024-06-09 by Ronaldo Faria Lima

   This file purpose: Functions to open a file
*/

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "fcb.h"

/**
 * Reads the FCB descriptor from the input file
 *
 * Parameters:
 * - fcb: FCB file to read size info from
 *
 * Returns:
 * - 0 in case of success
 * - -1 in case of failure
 */
static int
_read_file_header(const fcb_t *fcb)
{
  int rc;

  rc = fread(&(fcb->signature), sizeof(unsigned int), 1, fcp->fp);

  if (rc == 1)
    {
      if (fcp->signature != FCB_SIGNATURE)
        {
          /* No signature found in input file. We are trying to open
             something that is not a file generated by us. */
          return -1;
        }
      rc = fread(&(fcb->record_size), sizeof(size_t), 1, fcb->fp);
    }

  if (rc != 1)
    {
      return -1;
    }

  return 0;
}

fcb_t *
fcb_open(const char *fname, const char *mode)
{
  fcb_t *fcb;
  FILE *fp;

  if (!strchr(mode, 'b'))
    {
      /* FCB files are always opened in Binary mode */
      *errno = EINVAL;
      return NULL;
    }

  fp = fopen(fname, mode);
  if (fp == NULL)
    {
      return NULL;
    }

  fcb = (fcb_t *)malloc(sizeof(fcb_t));
  if (fcb == NULL)
    {
      return NULL;
    }

  memset(0x0, fcb, sizeof(fcb_t));
  fcb->fp = fp;

  /* If we are opening for writing, we don't want to get the FCB,
     since there is none */
  if (! strchr(mode, 'w'))
    {
      if (_read_file_header(fcb))
        {
          /* If we cannot read the file header from the input
             file, we fail.*/
          *errno = EINVAL;
          fclose(fcb->fp);
          free(fcb);
          return NULL;
        }
    }

  return fcb;
}
